### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by mykola-fant-ztu** [KinDofHell/book-pet#2]
- very long loading without a loader after page change;
- after sign-in went to Нотатки and ended up on this screen 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/488ee83c-764f-4233-be7b-a86086df0418)

- Збережене is just empty and non-clear 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/f71a49ce-2d97-4237-b14e-148a4b0858d3)
- Partial localisation 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/089ac523-a2ad-441e-8443-a85d8beed652)

- nit: after navigation in mobile view it would be better to close the menu 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/3d296888-9aef-4e7c-881a-50ea9eeb9fac)

- wrong button color for the light theme 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/23d53454-cfd9-4a14-883b-3c7caf7b6a3b)

- unhandled error if I add a note with the same name 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/4f295439-90d6-4a43-b3d4-33a370bd2f83)

- after I delete account and sign-up again I got this 
![image](https://github.com/KinDofHell/book-pet/assets/124682530/4073e08b-4a2a-4dbd-a8dd-f8360001f113)

**Comment by KinDofHell** [comment]
1. Provide spin loading for pages
2. I cannot reproduce bug with redirect after sign in(screen 1) neither on dev nor on prod
3. Add inscription and link to target page for 'saves' page if clear
4. I cannot configure it, clerk is independant service and there is no ukr lang
5. Navigation menu now close after click
6. Fix edit button color for light theme
7. Validation for note creating and handling errors
8. User will no longer be able to delete account
